import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react"
import { Providers } from "./providers"
import NavHeader from "../components/nav-header"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Program Evaluation",
  // description: "Generated by create next app",
};

import { Toaster } from "sonner";
import LayoutWrapper from "@/components/layoutWrapper";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Providers>
        <LayoutWrapper>
        {children}
        </LayoutWrapper>
  
          <Toaster position="top-right" richColors />
        </Providers>

      </body>
    </html>
  );
}
